### ISSUE TITLE
Parallel encoding

### ISSUE THREAD

**Issue by neofright** [spr/Oggify#12]
Do you think it is possible/worth looking into parallel encoding in Oggify?

**Comment by gbcox** [comment]
I created a project that duplicates much of the same functionality and also scales to use available CPUs, but uses bash instead of python. If you're using Fedora, it's in the official repository.  If not, just install the files in a directory, check to make sure you have the dependencies installed and execute.  https://bitbucket.org/gbcox/transflac/wiki/Home

**Comment by neofright** [comment]
Thanks @gbcox .

I switched to macOS for the first time in ~10yrs of using Fedora on the desktop. I'll see if I can create a fork of your transflac project and get it working with homebrew. Out of interest [this](https://github.com/neofright/rockbox-music-sync) was my old Bash script for doing the same thing.

**Comment by spr** [comment]
I think @gbcox has the best option. If you just need oggify's basic syncing functionality, transflac is going to do the job. It wouldn't be too hard to convert oggify to use the new async stuff in Python, but it's more time than I have right now.  Oggify is very out-of-date Python, which adds some complexity to using the newer python features.

**Comment by neofright** [comment]
@gbcox I created a GitHub copy of your BitBucket repo [here](https://github.com/neofright/transflac).

I've fixed some typos I found when using `nounset` and with some more changes I managed to get it to work 100% on macOS. Its churning through my 49018 flac files now!

I'm going to close this issue.

**Comment by gbcox** [comment]
> @gbcox I created a GitHub copy of your BitBucket repo [here](https://github.com/neofright/transflac).
> 
> I've fixed some typos I found when using `nounset` and with some more changes I managed to get it to work 100% on macOS. Its churning through my 49018 flac files now!
> 
> I'm going to close this issue.

I'm glad you were able to get it to work on macOS.  I'm going to go through your changes and typo fixes and see how those can be incorporated into baseline.  I did a quick look and see where you make excellent comments, so that will help.  Do you have a bitbucket account, maybe you could submit patches, if not no worries, I can add manually.  Again, glad it worked out for you and thanks for documenting what you changed so thoroughly.

**Comment by gbcox** [comment]
One other thought, what version of bash do you use on macOS?  I'm wondering if that could have caused an issue with some of the commands?  I'm just guessing, I haven't looked into it - but maybe worth a shot to try?  I know nothing about macOS, but found this:  https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

**Comment by neofright** [comment]
I tried to document some of the changes that were necessary on macOS [here](https://github.com/neofright/transflac/wiki). Specifically that I was invoking transflac with bash provided by homebrew `${HOMEBREW_PREFIX}/bin/bash`. I don't have a bitbucket account, I can make one if you'd like otherwise it might just be simpler to add manually.

Not all of my commits are straightforward, but I think you should be able to make sense of them, I'm really happy with where the program is now. Since I replied earlier on a 2020 M1 Macbook Pro I'm down to 13470/49018 (I had some time where the script was not running) and I'm really impressed with the encoding speed.

Thanks for creating transflac.
